---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
There's been a murder, a woman was killed,  
found in a bathtub, partially filled.  

A pair of policemen went into the house  
and questioned the poor woman's spouse.  

He'd just come home from working all night  
and found her like that, a terrible sight.  

The younger policeman looked on with dismay.  
He'd never forget that terrible day.  

He saw the young woman from behind the door  
and empty milk cartons all over the floor,  

Scattered strawberries, slices of fruit,  
and spoonfuls of sugar and honey to boot.  

''Who could have done this terrible thing?''  
His voice had a horrified, pitiful ring.  

''Just look at the clues,'' replied Sargeant Miller.  
''It looks like the work of a cereal killer.''  

